---

- name: SSH automation playbook
  hosts: localhost
  connection: local
  # remote_user: vagrant # I will have to use vagrant here

  tasks:
  - name: SSH Key Generation
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa_myproject
      type: rsa
      size: 4096
      state: present
      force: no

  # - name: SSH Key Deployment
  #   ansible.builtin.ping